name: Development

on: [push, pull_request]

jobs:

  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: '12.8'

      - name: npm cache
        uses: actions/cache@v1
        id: npm-cache
        with:
            path: ./src/node_modules
            key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json')}}-v2
            restore-keys: |
              ${{ runner.os }}-node-

      - name: install dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: |
          cd src 
          npm ci

      - name: protractor e2e tests
        run: |
          cd src
          npm run e2e

      - name: lint
        run: |
          cd src
          npm run lint

  test-e2e:
    runs-on: ubuntu-latest

    - name: Checkout
        uses: actions/checkout@v1
