name: Development

on: [push, pull_request]

jobs:

  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: cache node_modules
        id: npm-cache
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{runner.os}}-${{hashFiles('./src/package-lock.json')}}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: install packages
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: cd src && npm ci && cd -

  protractor-e2e:

    name: protractor e2e testing
    needs: install
    runs-on: ubuntu-latest

    steps:
      - name: Show directory
        run: ls -al
