name: Development

on: [push, pull_request]

jobs:

  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: cache node_modules
        id: npm-cache
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{runner.os}}-${{hashFiles('**/package-lock.json')}}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: install packages
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: cd src && npm ci && cd -

      - name: protractor e2e
        run: cd src && npm run e2e
