name: Development

on: [push, pull_request]

jobs:

  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: install packages
        run: cd src && npm install && cd -

      - name: persist data
        uses: actions/upload-artifact@v1
        with:
          name: source
          path: ./

  protractor-e2e:

    name: protractor e2e testing
    needs: install
    runs-on: ubuntu-latest

    steps:
      - name: Download Source Directory
        uses: actions/download-artifact@v1
        with:
          name: source

      - name: run protractor e2e
        run: ng e2e
  
  unit-tests:

    name: run unit tests
    needs: install
    runs-on: ubuntu-latest

    steps:
      - name: Download Source Directory
        uses: actions/download-artifact@v1
        with:
          name: source

      - name: run unit tests
        run: ng test
