name: Development

on: [push, pull_request]

jobs:

  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: '12.8'

      - name: install dependencies
        run: |
          cd src 
          npm install

      - name: protractor e2e tests
        run: |
          cd src
          npm run e2e
