name: Testing

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: install packages
        run: cd src && npm install
